// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/channelaccount"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ChannelAccountUpdate is the builder for updating ChannelAccount entities.
type ChannelAccountUpdate struct {
	config
	hooks     []Hook
	mutation  *ChannelAccountMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ChannelAccountUpdate builder.
func (_u *ChannelAccountUpdate) Where(ps ...predicate.ChannelAccount) *ChannelAccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChannelAccountUpdate) SetUpdatedAt(v time.Time) *ChannelAccountUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ChannelAccountUpdate) SetDeletedAt(v int) *ChannelAccountUpdate {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ChannelAccountUpdate) SetNillableDeletedAt(v *int) *ChannelAccountUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *ChannelAccountUpdate) AddDeletedAt(v int) *ChannelAccountUpdate {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ChannelAccountUpdate) SetName(v string) *ChannelAccountUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChannelAccountUpdate) SetNillableName(v *string) *ChannelAccountUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *ChannelAccountUpdate) ClearName() *ChannelAccountUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetIdentity sets the "identity" field.
func (_u *ChannelAccountUpdate) SetIdentity(v string) *ChannelAccountUpdate {
	_u.mutation.SetIdentity(v)
	return _u
}

// SetNillableIdentity sets the "identity" field if the given value is not nil.
func (_u *ChannelAccountUpdate) SetNillableIdentity(v *string) *ChannelAccountUpdate {
	if v != nil {
		_u.SetIdentity(*v)
	}
	return _u
}

// ClearIdentity clears the value of the "identity" field.
func (_u *ChannelAccountUpdate) ClearIdentity() *ChannelAccountUpdate {
	_u.mutation.ClearIdentity()
	return _u
}

// SetIdentityFingerprint sets the "identity_fingerprint" field.
func (_u *ChannelAccountUpdate) SetIdentityFingerprint(v string) *ChannelAccountUpdate {
	_u.mutation.SetIdentityFingerprint(v)
	return _u
}

// SetNillableIdentityFingerprint sets the "identity_fingerprint" field if the given value is not nil.
func (_u *ChannelAccountUpdate) SetNillableIdentityFingerprint(v *string) *ChannelAccountUpdate {
	if v != nil {
		_u.SetIdentityFingerprint(*v)
	}
	return _u
}

// ClearIdentityFingerprint clears the value of the "identity_fingerprint" field.
func (_u *ChannelAccountUpdate) ClearIdentityFingerprint() *ChannelAccountUpdate {
	_u.mutation.ClearIdentityFingerprint()
	return _u
}

// SetCredentialFingerprint sets the "credential_fingerprint" field.
func (_u *ChannelAccountUpdate) SetCredentialFingerprint(v string) *ChannelAccountUpdate {
	_u.mutation.SetCredentialFingerprint(v)
	return _u
}

// SetNillableCredentialFingerprint sets the "credential_fingerprint" field if the given value is not nil.
func (_u *ChannelAccountUpdate) SetNillableCredentialFingerprint(v *string) *ChannelAccountUpdate {
	if v != nil {
		_u.SetCredentialFingerprint(*v)
	}
	return _u
}

// SetCredentials sets the "credentials" field.
func (_u *ChannelAccountUpdate) SetCredentials(v map[string]interface{}) *ChannelAccountUpdate {
	_u.mutation.SetCredentials(v)
	return _u
}

// SetAuthState sets the "auth_state" field.
func (_u *ChannelAccountUpdate) SetAuthState(v channelaccount.AuthState) *ChannelAccountUpdate {
	_u.mutation.SetAuthState(v)
	return _u
}

// SetNillableAuthState sets the "auth_state" field if the given value is not nil.
func (_u *ChannelAccountUpdate) SetNillableAuthState(v *channelaccount.AuthState) *ChannelAccountUpdate {
	if v != nil {
		_u.SetAuthState(*v)
	}
	return _u
}

// SetAuthErrorCode sets the "auth_error_code" field.
func (_u *ChannelAccountUpdate) SetAuthErrorCode(v string) *ChannelAccountUpdate {
	_u.mutation.SetAuthErrorCode(v)
	return _u
}

// SetNillableAuthErrorCode sets the "auth_error_code" field if the given value is not nil.
func (_u *ChannelAccountUpdate) SetNillableAuthErrorCode(v *string) *ChannelAccountUpdate {
	if v != nil {
		_u.SetAuthErrorCode(*v)
	}
	return _u
}

// ClearAuthErrorCode clears the value of the "auth_error_code" field.
func (_u *ChannelAccountUpdate) ClearAuthErrorCode() *ChannelAccountUpdate {
	_u.mutation.ClearAuthErrorCode()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ChannelAccountUpdate) SetEnabled(v bool) *ChannelAccountUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ChannelAccountUpdate) SetNillableEnabled(v *bool) *ChannelAccountUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetWeight sets the "weight" field.
func (_u *ChannelAccountUpdate) SetWeight(v int) *ChannelAccountUpdate {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *ChannelAccountUpdate) SetNillableWeight(v *int) *ChannelAccountUpdate {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *ChannelAccountUpdate) AddWeight(v int) *ChannelAccountUpdate {
	_u.mutation.AddWeight(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ChannelAccountUpdate) SetExpiresAt(v time.Time) *ChannelAccountUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ChannelAccountUpdate) SetNillableExpiresAt(v *time.Time) *ChannelAccountUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ChannelAccountUpdate) ClearExpiresAt() *ChannelAccountUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetLastRefreshAt sets the "last_refresh_at" field.
func (_u *ChannelAccountUpdate) SetLastRefreshAt(v time.Time) *ChannelAccountUpdate {
	_u.mutation.SetLastRefreshAt(v)
	return _u
}

// SetNillableLastRefreshAt sets the "last_refresh_at" field if the given value is not nil.
func (_u *ChannelAccountUpdate) SetNillableLastRefreshAt(v *time.Time) *ChannelAccountUpdate {
	if v != nil {
		_u.SetLastRefreshAt(*v)
	}
	return _u
}

// ClearLastRefreshAt clears the value of the "last_refresh_at" field.
func (_u *ChannelAccountUpdate) ClearLastRefreshAt() *ChannelAccountUpdate {
	_u.mutation.ClearLastRefreshAt()
	return _u
}

// Mutation returns the ChannelAccountMutation object of the builder.
func (_u *ChannelAccountUpdate) Mutation() *ChannelAccountMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChannelAccountUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChannelAccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelAccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChannelAccountUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if channelaccount.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized channelaccount.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := channelaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelAccountUpdate) check() error {
	if v, ok := _u.mutation.AuthState(); ok {
		if err := channelaccount.AuthStateValidator(v); err != nil {
			return &ValidationError{Name: "auth_state", err: fmt.Errorf(`ent: validator failed for field "ChannelAccount.auth_state": %w`, err)}
		}
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelAccount.channel"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ChannelAccountUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ChannelAccountUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ChannelAccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelaccount.Table, channelaccount.Columns, sqlgraph.NewFieldSpec(channelaccount.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(channelaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(channelaccount.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(channelaccount.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(channelaccount.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(channelaccount.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Identity(); ok {
		_spec.SetField(channelaccount.FieldIdentity, field.TypeString, value)
	}
	if _u.mutation.IdentityCleared() {
		_spec.ClearField(channelaccount.FieldIdentity, field.TypeString)
	}
	if value, ok := _u.mutation.IdentityFingerprint(); ok {
		_spec.SetField(channelaccount.FieldIdentityFingerprint, field.TypeString, value)
	}
	if _u.mutation.IdentityFingerprintCleared() {
		_spec.ClearField(channelaccount.FieldIdentityFingerprint, field.TypeString)
	}
	if value, ok := _u.mutation.CredentialFingerprint(); ok {
		_spec.SetField(channelaccount.FieldCredentialFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Credentials(); ok {
		_spec.SetField(channelaccount.FieldCredentials, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AuthState(); ok {
		_spec.SetField(channelaccount.FieldAuthState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AuthErrorCode(); ok {
		_spec.SetField(channelaccount.FieldAuthErrorCode, field.TypeString, value)
	}
	if _u.mutation.AuthErrorCodeCleared() {
		_spec.ClearField(channelaccount.FieldAuthErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(channelaccount.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(channelaccount.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(channelaccount.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(channelaccount.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(channelaccount.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastRefreshAt(); ok {
		_spec.SetField(channelaccount.FieldLastRefreshAt, field.TypeTime, value)
	}
	if _u.mutation.LastRefreshAtCleared() {
		_spec.ClearField(channelaccount.FieldLastRefreshAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChannelAccountUpdateOne is the builder for updating a single ChannelAccount entity.
type ChannelAccountUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ChannelAccountMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChannelAccountUpdateOne) SetUpdatedAt(v time.Time) *ChannelAccountUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ChannelAccountUpdateOne) SetDeletedAt(v int) *ChannelAccountUpdateOne {
	_u.mutation.ResetDeletedAt()
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ChannelAccountUpdateOne) SetNillableDeletedAt(v *int) *ChannelAccountUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// AddDeletedAt adds value to the "deleted_at" field.
func (_u *ChannelAccountUpdateOne) AddDeletedAt(v int) *ChannelAccountUpdateOne {
	_u.mutation.AddDeletedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *ChannelAccountUpdateOne) SetName(v string) *ChannelAccountUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChannelAccountUpdateOne) SetNillableName(v *string) *ChannelAccountUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *ChannelAccountUpdateOne) ClearName() *ChannelAccountUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetIdentity sets the "identity" field.
func (_u *ChannelAccountUpdateOne) SetIdentity(v string) *ChannelAccountUpdateOne {
	_u.mutation.SetIdentity(v)
	return _u
}

// SetNillableIdentity sets the "identity" field if the given value is not nil.
func (_u *ChannelAccountUpdateOne) SetNillableIdentity(v *string) *ChannelAccountUpdateOne {
	if v != nil {
		_u.SetIdentity(*v)
	}
	return _u
}

// ClearIdentity clears the value of the "identity" field.
func (_u *ChannelAccountUpdateOne) ClearIdentity() *ChannelAccountUpdateOne {
	_u.mutation.ClearIdentity()
	return _u
}

// SetIdentityFingerprint sets the "identity_fingerprint" field.
func (_u *ChannelAccountUpdateOne) SetIdentityFingerprint(v string) *ChannelAccountUpdateOne {
	_u.mutation.SetIdentityFingerprint(v)
	return _u
}

// SetNillableIdentityFingerprint sets the "identity_fingerprint" field if the given value is not nil.
func (_u *ChannelAccountUpdateOne) SetNillableIdentityFingerprint(v *string) *ChannelAccountUpdateOne {
	if v != nil {
		_u.SetIdentityFingerprint(*v)
	}
	return _u
}

// ClearIdentityFingerprint clears the value of the "identity_fingerprint" field.
func (_u *ChannelAccountUpdateOne) ClearIdentityFingerprint() *ChannelAccountUpdateOne {
	_u.mutation.ClearIdentityFingerprint()
	return _u
}

// SetCredentialFingerprint sets the "credential_fingerprint" field.
func (_u *ChannelAccountUpdateOne) SetCredentialFingerprint(v string) *ChannelAccountUpdateOne {
	_u.mutation.SetCredentialFingerprint(v)
	return _u
}

// SetNillableCredentialFingerprint sets the "credential_fingerprint" field if the given value is not nil.
func (_u *ChannelAccountUpdateOne) SetNillableCredentialFingerprint(v *string) *ChannelAccountUpdateOne {
	if v != nil {
		_u.SetCredentialFingerprint(*v)
	}
	return _u
}

// SetCredentials sets the "credentials" field.
func (_u *ChannelAccountUpdateOne) SetCredentials(v map[string]interface{}) *ChannelAccountUpdateOne {
	_u.mutation.SetCredentials(v)
	return _u
}

// SetAuthState sets the "auth_state" field.
func (_u *ChannelAccountUpdateOne) SetAuthState(v channelaccount.AuthState) *ChannelAccountUpdateOne {
	_u.mutation.SetAuthState(v)
	return _u
}

// SetNillableAuthState sets the "auth_state" field if the given value is not nil.
func (_u *ChannelAccountUpdateOne) SetNillableAuthState(v *channelaccount.AuthState) *ChannelAccountUpdateOne {
	if v != nil {
		_u.SetAuthState(*v)
	}
	return _u
}

// SetAuthErrorCode sets the "auth_error_code" field.
func (_u *ChannelAccountUpdateOne) SetAuthErrorCode(v string) *ChannelAccountUpdateOne {
	_u.mutation.SetAuthErrorCode(v)
	return _u
}

// SetNillableAuthErrorCode sets the "auth_error_code" field if the given value is not nil.
func (_u *ChannelAccountUpdateOne) SetNillableAuthErrorCode(v *string) *ChannelAccountUpdateOne {
	if v != nil {
		_u.SetAuthErrorCode(*v)
	}
	return _u
}

// ClearAuthErrorCode clears the value of the "auth_error_code" field.
func (_u *ChannelAccountUpdateOne) ClearAuthErrorCode() *ChannelAccountUpdateOne {
	_u.mutation.ClearAuthErrorCode()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ChannelAccountUpdateOne) SetEnabled(v bool) *ChannelAccountUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ChannelAccountUpdateOne) SetNillableEnabled(v *bool) *ChannelAccountUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetWeight sets the "weight" field.
func (_u *ChannelAccountUpdateOne) SetWeight(v int) *ChannelAccountUpdateOne {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *ChannelAccountUpdateOne) SetNillableWeight(v *int) *ChannelAccountUpdateOne {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *ChannelAccountUpdateOne) AddWeight(v int) *ChannelAccountUpdateOne {
	_u.mutation.AddWeight(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ChannelAccountUpdateOne) SetExpiresAt(v time.Time) *ChannelAccountUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ChannelAccountUpdateOne) SetNillableExpiresAt(v *time.Time) *ChannelAccountUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ChannelAccountUpdateOne) ClearExpiresAt() *ChannelAccountUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetLastRefreshAt sets the "last_refresh_at" field.
func (_u *ChannelAccountUpdateOne) SetLastRefreshAt(v time.Time) *ChannelAccountUpdateOne {
	_u.mutation.SetLastRefreshAt(v)
	return _u
}

// SetNillableLastRefreshAt sets the "last_refresh_at" field if the given value is not nil.
func (_u *ChannelAccountUpdateOne) SetNillableLastRefreshAt(v *time.Time) *ChannelAccountUpdateOne {
	if v != nil {
		_u.SetLastRefreshAt(*v)
	}
	return _u
}

// ClearLastRefreshAt clears the value of the "last_refresh_at" field.
func (_u *ChannelAccountUpdateOne) ClearLastRefreshAt() *ChannelAccountUpdateOne {
	_u.mutation.ClearLastRefreshAt()
	return _u
}

// Mutation returns the ChannelAccountMutation object of the builder.
func (_u *ChannelAccountUpdateOne) Mutation() *ChannelAccountMutation {
	return _u.mutation
}

// Where appends a list predicates to the ChannelAccountUpdate builder.
func (_u *ChannelAccountUpdateOne) Where(ps ...predicate.ChannelAccount) *ChannelAccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChannelAccountUpdateOne) Select(field string, fields ...string) *ChannelAccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChannelAccount entity.
func (_u *ChannelAccountUpdateOne) Save(ctx context.Context) (*ChannelAccount, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChannelAccountUpdateOne) SaveX(ctx context.Context) *ChannelAccount {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChannelAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChannelAccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChannelAccountUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if channelaccount.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized channelaccount.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := channelaccount.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChannelAccountUpdateOne) check() error {
	if v, ok := _u.mutation.AuthState(); ok {
		if err := channelaccount.AuthStateValidator(v); err != nil {
			return &ValidationError{Name: "auth_state", err: fmt.Errorf(`ent: validator failed for field "ChannelAccount.auth_state": %w`, err)}
		}
	}
	if _u.mutation.ChannelCleared() && len(_u.mutation.ChannelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChannelAccount.channel"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ChannelAccountUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ChannelAccountUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ChannelAccountUpdateOne) sqlSave(ctx context.Context) (_node *ChannelAccount, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(channelaccount.Table, channelaccount.Columns, sqlgraph.NewFieldSpec(channelaccount.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChannelAccount.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, channelaccount.FieldID)
		for _, f := range fields {
			if !channelaccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != channelaccount.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(channelaccount.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(channelaccount.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedAt(); ok {
		_spec.AddField(channelaccount.FieldDeletedAt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(channelaccount.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(channelaccount.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Identity(); ok {
		_spec.SetField(channelaccount.FieldIdentity, field.TypeString, value)
	}
	if _u.mutation.IdentityCleared() {
		_spec.ClearField(channelaccount.FieldIdentity, field.TypeString)
	}
	if value, ok := _u.mutation.IdentityFingerprint(); ok {
		_spec.SetField(channelaccount.FieldIdentityFingerprint, field.TypeString, value)
	}
	if _u.mutation.IdentityFingerprintCleared() {
		_spec.ClearField(channelaccount.FieldIdentityFingerprint, field.TypeString)
	}
	if value, ok := _u.mutation.CredentialFingerprint(); ok {
		_spec.SetField(channelaccount.FieldCredentialFingerprint, field.TypeString, value)
	}
	if value, ok := _u.mutation.Credentials(); ok {
		_spec.SetField(channelaccount.FieldCredentials, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AuthState(); ok {
		_spec.SetField(channelaccount.FieldAuthState, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.AuthErrorCode(); ok {
		_spec.SetField(channelaccount.FieldAuthErrorCode, field.TypeString, value)
	}
	if _u.mutation.AuthErrorCodeCleared() {
		_spec.ClearField(channelaccount.FieldAuthErrorCode, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(channelaccount.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(channelaccount.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(channelaccount.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(channelaccount.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(channelaccount.FieldExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastRefreshAt(); ok {
		_spec.SetField(channelaccount.FieldLastRefreshAt, field.TypeTime, value)
	}
	if _u.mutation.LastRefreshAtCleared() {
		_spec.ClearField(channelaccount.FieldLastRefreshAt, field.TypeTime)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ChannelAccount{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{channelaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
