// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/channelaccount"
)

// ChannelAccount is the model entity for the ChannelAccount schema.
type ChannelAccount struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt int `json:"deleted_at,omitempty"`
	// ChannelID holds the value of the "channel_id" field.
	ChannelID int `json:"channel_id,omitempty"`
	// Operator-facing label. Often the account email, but never required to be.
	Name string `json:"name,omitempty"`
	// Upstream account identity, e.g. the Google account id or the Anthropic account/organization uuid. Empty until the grant is parsed.
	Identity string `json:"identity,omitempty"`
	// Stable digest of the identity, used to detect re-authorization of the same account.
	IdentityFingerprint string `json:"identity_fingerprint,omitempty"`
	// The granted credential. Its shape is owned by the provider transformer, not by this schema.
	Credentials map[string]interface{} `json:"-"`
	// Lifecycle of the grant. Only a ready account serves traffic.
	AuthState channelaccount.AuthState `json:"auth_state,omitempty"`
	// Machine-readable reason the account is not ready. Safe to log: never carries credential material.
	AuthErrorCode string `json:"auth_error_code,omitempty"`
	// Operator-controlled switch, independent of auth_state.
	Enabled bool `json:"enabled,omitempty"`
	// Relative share of traffic among a channel's accounts. Zero pauses the account while keeping its history.
	Weight int `json:"weight,omitempty"`
	// When the access token expires. Nil when the grant does not expire.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// Last successful token refresh, for observability.
	LastRefreshAt *time.Time `json:"last_refresh_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChannelAccountQuery when eager-loading is set.
	Edges        ChannelAccountEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ChannelAccountEdges holds the relations/edges for other nodes in the graph.
type ChannelAccountEdges struct {
	// Channel holds the value of the channel edge.
	Channel *Channel `json:"channel,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int
}

// ChannelOrErr returns the Channel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChannelAccountEdges) ChannelOrErr() (*Channel, error) {
	if e.Channel != nil {
		return e.Channel, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: channel.Label}
	}
	return nil, &NotLoadedError{edge: "channel"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChannelAccount) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case channelaccount.FieldCredentials:
			values[i] = new([]byte)
		case channelaccount.FieldEnabled:
			values[i] = new(sql.NullBool)
		case channelaccount.FieldID, channelaccount.FieldDeletedAt, channelaccount.FieldChannelID, channelaccount.FieldWeight:
			values[i] = new(sql.NullInt64)
		case channelaccount.FieldName, channelaccount.FieldIdentity, channelaccount.FieldIdentityFingerprint, channelaccount.FieldAuthState, channelaccount.FieldAuthErrorCode:
			values[i] = new(sql.NullString)
		case channelaccount.FieldCreatedAt, channelaccount.FieldUpdatedAt, channelaccount.FieldExpiresAt, channelaccount.FieldLastRefreshAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChannelAccount fields.
func (_m *ChannelAccount) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case channelaccount.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case channelaccount.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case channelaccount.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case channelaccount.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = int(value.Int64)
			}
		case channelaccount.FieldChannelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field channel_id", values[i])
			} else if value.Valid {
				_m.ChannelID = int(value.Int64)
			}
		case channelaccount.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case channelaccount.FieldIdentity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field identity", values[i])
			} else if value.Valid {
				_m.Identity = value.String
			}
		case channelaccount.FieldIdentityFingerprint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field identity_fingerprint", values[i])
			} else if value.Valid {
				_m.IdentityFingerprint = value.String
			}
		case channelaccount.FieldCredentials:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field credentials", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Credentials); err != nil {
					return fmt.Errorf("unmarshal field credentials: %w", err)
				}
			}
		case channelaccount.FieldAuthState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_state", values[i])
			} else if value.Valid {
				_m.AuthState = channelaccount.AuthState(value.String)
			}
		case channelaccount.FieldAuthErrorCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_error_code", values[i])
			} else if value.Valid {
				_m.AuthErrorCode = value.String
			}
		case channelaccount.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case channelaccount.FieldWeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field weight", values[i])
			} else if value.Valid {
				_m.Weight = int(value.Int64)
			}
		case channelaccount.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case channelaccount.FieldLastRefreshAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_refresh_at", values[i])
			} else if value.Valid {
				_m.LastRefreshAt = new(time.Time)
				*_m.LastRefreshAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChannelAccount.
// This includes values selected through modifiers, order, etc.
func (_m *ChannelAccount) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChannel queries the "channel" edge of the ChannelAccount entity.
func (_m *ChannelAccount) QueryChannel() *ChannelQuery {
	return NewChannelAccountClient(_m.config).QueryChannel(_m)
}

// Update returns a builder for updating this ChannelAccount.
// Note that you need to call ChannelAccount.Unwrap() before calling this method if this ChannelAccount
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChannelAccount) Update() *ChannelAccountUpdateOne {
	return NewChannelAccountClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChannelAccount entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChannelAccount) Unwrap() *ChannelAccount {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChannelAccount is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChannelAccount) String() string {
	var builder strings.Builder
	builder.WriteString("ChannelAccount(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedAt))
	builder.WriteString(", ")
	builder.WriteString("channel_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChannelID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("identity=")
	builder.WriteString(_m.Identity)
	builder.WriteString(", ")
	builder.WriteString("identity_fingerprint=")
	builder.WriteString(_m.IdentityFingerprint)
	builder.WriteString(", ")
	builder.WriteString("credentials=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("auth_state=")
	builder.WriteString(fmt.Sprintf("%v", _m.AuthState))
	builder.WriteString(", ")
	builder.WriteString("auth_error_code=")
	builder.WriteString(_m.AuthErrorCode)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("weight=")
	builder.WriteString(fmt.Sprintf("%v", _m.Weight))
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastRefreshAt; v != nil {
		builder.WriteString("last_refresh_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ChannelAccounts is a parsable slice of ChannelAccount.
type ChannelAccounts []*ChannelAccount
