// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/looplj/axonhub/internal/ent/channel"
	"github.com/looplj/axonhub/internal/ent/channelaccount"
)

// ChannelAccountCreate is the builder for creating a ChannelAccount entity.
type ChannelAccountCreate struct {
	config
	mutation *ChannelAccountMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChannelAccountCreate) SetCreatedAt(v time.Time) *ChannelAccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChannelAccountCreate) SetNillableCreatedAt(v *time.Time) *ChannelAccountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChannelAccountCreate) SetUpdatedAt(v time.Time) *ChannelAccountCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChannelAccountCreate) SetNillableUpdatedAt(v *time.Time) *ChannelAccountCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ChannelAccountCreate) SetDeletedAt(v int) *ChannelAccountCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ChannelAccountCreate) SetNillableDeletedAt(v *int) *ChannelAccountCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetChannelID sets the "channel_id" field.
func (_c *ChannelAccountCreate) SetChannelID(v int) *ChannelAccountCreate {
	_c.mutation.SetChannelID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ChannelAccountCreate) SetName(v string) *ChannelAccountCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *ChannelAccountCreate) SetNillableName(v *string) *ChannelAccountCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetIdentity sets the "identity" field.
func (_c *ChannelAccountCreate) SetIdentity(v string) *ChannelAccountCreate {
	_c.mutation.SetIdentity(v)
	return _c
}

// SetNillableIdentity sets the "identity" field if the given value is not nil.
func (_c *ChannelAccountCreate) SetNillableIdentity(v *string) *ChannelAccountCreate {
	if v != nil {
		_c.SetIdentity(*v)
	}
	return _c
}

// SetIdentityFingerprint sets the "identity_fingerprint" field.
func (_c *ChannelAccountCreate) SetIdentityFingerprint(v string) *ChannelAccountCreate {
	_c.mutation.SetIdentityFingerprint(v)
	return _c
}

// SetNillableIdentityFingerprint sets the "identity_fingerprint" field if the given value is not nil.
func (_c *ChannelAccountCreate) SetNillableIdentityFingerprint(v *string) *ChannelAccountCreate {
	if v != nil {
		_c.SetIdentityFingerprint(*v)
	}
	return _c
}

// SetCredentials sets the "credentials" field.
func (_c *ChannelAccountCreate) SetCredentials(v map[string]interface{}) *ChannelAccountCreate {
	_c.mutation.SetCredentials(v)
	return _c
}

// SetAuthState sets the "auth_state" field.
func (_c *ChannelAccountCreate) SetAuthState(v channelaccount.AuthState) *ChannelAccountCreate {
	_c.mutation.SetAuthState(v)
	return _c
}

// SetNillableAuthState sets the "auth_state" field if the given value is not nil.
func (_c *ChannelAccountCreate) SetNillableAuthState(v *channelaccount.AuthState) *ChannelAccountCreate {
	if v != nil {
		_c.SetAuthState(*v)
	}
	return _c
}

// SetAuthErrorCode sets the "auth_error_code" field.
func (_c *ChannelAccountCreate) SetAuthErrorCode(v string) *ChannelAccountCreate {
	_c.mutation.SetAuthErrorCode(v)
	return _c
}

// SetNillableAuthErrorCode sets the "auth_error_code" field if the given value is not nil.
func (_c *ChannelAccountCreate) SetNillableAuthErrorCode(v *string) *ChannelAccountCreate {
	if v != nil {
		_c.SetAuthErrorCode(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *ChannelAccountCreate) SetEnabled(v bool) *ChannelAccountCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *ChannelAccountCreate) SetNillableEnabled(v *bool) *ChannelAccountCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetWeight sets the "weight" field.
func (_c *ChannelAccountCreate) SetWeight(v int) *ChannelAccountCreate {
	_c.mutation.SetWeight(v)
	return _c
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_c *ChannelAccountCreate) SetNillableWeight(v *int) *ChannelAccountCreate {
	if v != nil {
		_c.SetWeight(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *ChannelAccountCreate) SetExpiresAt(v time.Time) *ChannelAccountCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *ChannelAccountCreate) SetNillableExpiresAt(v *time.Time) *ChannelAccountCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetLastRefreshAt sets the "last_refresh_at" field.
func (_c *ChannelAccountCreate) SetLastRefreshAt(v time.Time) *ChannelAccountCreate {
	_c.mutation.SetLastRefreshAt(v)
	return _c
}

// SetNillableLastRefreshAt sets the "last_refresh_at" field if the given value is not nil.
func (_c *ChannelAccountCreate) SetNillableLastRefreshAt(v *time.Time) *ChannelAccountCreate {
	if v != nil {
		_c.SetLastRefreshAt(*v)
	}
	return _c
}

// SetChannel sets the "channel" edge to the Channel entity.
func (_c *ChannelAccountCreate) SetChannel(v *Channel) *ChannelAccountCreate {
	return _c.SetChannelID(v.ID)
}

// Mutation returns the ChannelAccountMutation object of the builder.
func (_c *ChannelAccountCreate) Mutation() *ChannelAccountMutation {
	return _c.mutation
}

// Save creates the ChannelAccount in the database.
func (_c *ChannelAccountCreate) Save(ctx context.Context) (*ChannelAccount, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChannelAccountCreate) SaveX(ctx context.Context) *ChannelAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelAccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelAccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChannelAccountCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if channelaccount.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized channelaccount.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := channelaccount.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if channelaccount.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized channelaccount.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := channelaccount.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DeletedAt(); !ok {
		v := channelaccount.DefaultDeletedAt
		_c.mutation.SetDeletedAt(v)
	}
	if _, ok := _c.mutation.Name(); !ok {
		v := channelaccount.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.Identity(); !ok {
		v := channelaccount.DefaultIdentity
		_c.mutation.SetIdentity(v)
	}
	if _, ok := _c.mutation.IdentityFingerprint(); !ok {
		v := channelaccount.DefaultIdentityFingerprint
		_c.mutation.SetIdentityFingerprint(v)
	}
	if _, ok := _c.mutation.AuthState(); !ok {
		v := channelaccount.DefaultAuthState
		_c.mutation.SetAuthState(v)
	}
	if _, ok := _c.mutation.AuthErrorCode(); !ok {
		v := channelaccount.DefaultAuthErrorCode
		_c.mutation.SetAuthErrorCode(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := channelaccount.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Weight(); !ok {
		v := channelaccount.DefaultWeight
		_c.mutation.SetWeight(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChannelAccountCreate) check() error {
	if _, ok := _c.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "ChannelAccount.deleted_at"`)}
	}
	if _, ok := _c.mutation.ChannelID(); !ok {
		return &ValidationError{Name: "channel_id", err: errors.New(`ent: missing required field "ChannelAccount.channel_id"`)}
	}
	if _, ok := _c.mutation.Credentials(); !ok {
		return &ValidationError{Name: "credentials", err: errors.New(`ent: missing required field "ChannelAccount.credentials"`)}
	}
	if _, ok := _c.mutation.AuthState(); !ok {
		return &ValidationError{Name: "auth_state", err: errors.New(`ent: missing required field "ChannelAccount.auth_state"`)}
	}
	if v, ok := _c.mutation.AuthState(); ok {
		if err := channelaccount.AuthStateValidator(v); err != nil {
			return &ValidationError{Name: "auth_state", err: fmt.Errorf(`ent: validator failed for field "ChannelAccount.auth_state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "ChannelAccount.enabled"`)}
	}
	if _, ok := _c.mutation.Weight(); !ok {
		return &ValidationError{Name: "weight", err: errors.New(`ent: missing required field "ChannelAccount.weight"`)}
	}
	if len(_c.mutation.ChannelIDs()) == 0 {
		return &ValidationError{Name: "channel", err: errors.New(`ent: missing required edge "ChannelAccount.channel"`)}
	}
	return nil
}

func (_c *ChannelAccountCreate) sqlSave(ctx context.Context) (*ChannelAccount, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChannelAccountCreate) createSpec() (*ChannelAccount, *sqlgraph.CreateSpec) {
	var (
		_node = &ChannelAccount{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(channelaccount.Table, sqlgraph.NewFieldSpec(channelaccount.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(channelaccount.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(channelaccount.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(channelaccount.FieldDeletedAt, field.TypeInt, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(channelaccount.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Identity(); ok {
		_spec.SetField(channelaccount.FieldIdentity, field.TypeString, value)
		_node.Identity = value
	}
	if value, ok := _c.mutation.IdentityFingerprint(); ok {
		_spec.SetField(channelaccount.FieldIdentityFingerprint, field.TypeString, value)
		_node.IdentityFingerprint = value
	}
	if value, ok := _c.mutation.Credentials(); ok {
		_spec.SetField(channelaccount.FieldCredentials, field.TypeJSON, value)
		_node.Credentials = value
	}
	if value, ok := _c.mutation.AuthState(); ok {
		_spec.SetField(channelaccount.FieldAuthState, field.TypeEnum, value)
		_node.AuthState = value
	}
	if value, ok := _c.mutation.AuthErrorCode(); ok {
		_spec.SetField(channelaccount.FieldAuthErrorCode, field.TypeString, value)
		_node.AuthErrorCode = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(channelaccount.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Weight(); ok {
		_spec.SetField(channelaccount.FieldWeight, field.TypeInt, value)
		_node.Weight = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(channelaccount.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.LastRefreshAt(); ok {
		_spec.SetField(channelaccount.FieldLastRefreshAt, field.TypeTime, value)
		_node.LastRefreshAt = &value
	}
	if nodes := _c.mutation.ChannelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelaccount.ChannelTable,
			Columns: []string{channelaccount.ChannelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channel.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChannelID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChannelAccount.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChannelAccountUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ChannelAccountCreate) OnConflict(opts ...sql.ConflictOption) *ChannelAccountUpsertOne {
	_c.conflict = opts
	return &ChannelAccountUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChannelAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChannelAccountCreate) OnConflictColumns(columns ...string) *ChannelAccountUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChannelAccountUpsertOne{
		create: _c,
	}
}

type (
	// ChannelAccountUpsertOne is the builder for "upsert"-ing
	//  one ChannelAccount node.
	ChannelAccountUpsertOne struct {
		create *ChannelAccountCreate
	}

	// ChannelAccountUpsert is the "OnConflict" setter.
	ChannelAccountUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelAccountUpsert) SetUpdatedAt(v time.Time) *ChannelAccountUpsert {
	u.Set(channelaccount.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelAccountUpsert) UpdateUpdatedAt() *ChannelAccountUpsert {
	u.SetExcluded(channelaccount.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ChannelAccountUpsert) SetDeletedAt(v int) *ChannelAccountUpsert {
	u.Set(channelaccount.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ChannelAccountUpsert) UpdateDeletedAt() *ChannelAccountUpsert {
	u.SetExcluded(channelaccount.FieldDeletedAt)
	return u
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *ChannelAccountUpsert) AddDeletedAt(v int) *ChannelAccountUpsert {
	u.Add(channelaccount.FieldDeletedAt, v)
	return u
}

// SetName sets the "name" field.
func (u *ChannelAccountUpsert) SetName(v string) *ChannelAccountUpsert {
	u.Set(channelaccount.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ChannelAccountUpsert) UpdateName() *ChannelAccountUpsert {
	u.SetExcluded(channelaccount.FieldName)
	return u
}

// ClearName clears the value of the "name" field.
func (u *ChannelAccountUpsert) ClearName() *ChannelAccountUpsert {
	u.SetNull(channelaccount.FieldName)
	return u
}

// SetIdentity sets the "identity" field.
func (u *ChannelAccountUpsert) SetIdentity(v string) *ChannelAccountUpsert {
	u.Set(channelaccount.FieldIdentity, v)
	return u
}

// UpdateIdentity sets the "identity" field to the value that was provided on create.
func (u *ChannelAccountUpsert) UpdateIdentity() *ChannelAccountUpsert {
	u.SetExcluded(channelaccount.FieldIdentity)
	return u
}

// ClearIdentity clears the value of the "identity" field.
func (u *ChannelAccountUpsert) ClearIdentity() *ChannelAccountUpsert {
	u.SetNull(channelaccount.FieldIdentity)
	return u
}

// SetIdentityFingerprint sets the "identity_fingerprint" field.
func (u *ChannelAccountUpsert) SetIdentityFingerprint(v string) *ChannelAccountUpsert {
	u.Set(channelaccount.FieldIdentityFingerprint, v)
	return u
}

// UpdateIdentityFingerprint sets the "identity_fingerprint" field to the value that was provided on create.
func (u *ChannelAccountUpsert) UpdateIdentityFingerprint() *ChannelAccountUpsert {
	u.SetExcluded(channelaccount.FieldIdentityFingerprint)
	return u
}

// ClearIdentityFingerprint clears the value of the "identity_fingerprint" field.
func (u *ChannelAccountUpsert) ClearIdentityFingerprint() *ChannelAccountUpsert {
	u.SetNull(channelaccount.FieldIdentityFingerprint)
	return u
}

// SetCredentials sets the "credentials" field.
func (u *ChannelAccountUpsert) SetCredentials(v map[string]interface{}) *ChannelAccountUpsert {
	u.Set(channelaccount.FieldCredentials, v)
	return u
}

// UpdateCredentials sets the "credentials" field to the value that was provided on create.
func (u *ChannelAccountUpsert) UpdateCredentials() *ChannelAccountUpsert {
	u.SetExcluded(channelaccount.FieldCredentials)
	return u
}

// SetAuthState sets the "auth_state" field.
func (u *ChannelAccountUpsert) SetAuthState(v channelaccount.AuthState) *ChannelAccountUpsert {
	u.Set(channelaccount.FieldAuthState, v)
	return u
}

// UpdateAuthState sets the "auth_state" field to the value that was provided on create.
func (u *ChannelAccountUpsert) UpdateAuthState() *ChannelAccountUpsert {
	u.SetExcluded(channelaccount.FieldAuthState)
	return u
}

// SetAuthErrorCode sets the "auth_error_code" field.
func (u *ChannelAccountUpsert) SetAuthErrorCode(v string) *ChannelAccountUpsert {
	u.Set(channelaccount.FieldAuthErrorCode, v)
	return u
}

// UpdateAuthErrorCode sets the "auth_error_code" field to the value that was provided on create.
func (u *ChannelAccountUpsert) UpdateAuthErrorCode() *ChannelAccountUpsert {
	u.SetExcluded(channelaccount.FieldAuthErrorCode)
	return u
}

// ClearAuthErrorCode clears the value of the "auth_error_code" field.
func (u *ChannelAccountUpsert) ClearAuthErrorCode() *ChannelAccountUpsert {
	u.SetNull(channelaccount.FieldAuthErrorCode)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *ChannelAccountUpsert) SetEnabled(v bool) *ChannelAccountUpsert {
	u.Set(channelaccount.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ChannelAccountUpsert) UpdateEnabled() *ChannelAccountUpsert {
	u.SetExcluded(channelaccount.FieldEnabled)
	return u
}

// SetWeight sets the "weight" field.
func (u *ChannelAccountUpsert) SetWeight(v int) *ChannelAccountUpsert {
	u.Set(channelaccount.FieldWeight, v)
	return u
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *ChannelAccountUpsert) UpdateWeight() *ChannelAccountUpsert {
	u.SetExcluded(channelaccount.FieldWeight)
	return u
}

// AddWeight adds v to the "weight" field.
func (u *ChannelAccountUpsert) AddWeight(v int) *ChannelAccountUpsert {
	u.Add(channelaccount.FieldWeight, v)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *ChannelAccountUpsert) SetExpiresAt(v time.Time) *ChannelAccountUpsert {
	u.Set(channelaccount.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ChannelAccountUpsert) UpdateExpiresAt() *ChannelAccountUpsert {
	u.SetExcluded(channelaccount.FieldExpiresAt)
	return u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ChannelAccountUpsert) ClearExpiresAt() *ChannelAccountUpsert {
	u.SetNull(channelaccount.FieldExpiresAt)
	return u
}

// SetLastRefreshAt sets the "last_refresh_at" field.
func (u *ChannelAccountUpsert) SetLastRefreshAt(v time.Time) *ChannelAccountUpsert {
	u.Set(channelaccount.FieldLastRefreshAt, v)
	return u
}

// UpdateLastRefreshAt sets the "last_refresh_at" field to the value that was provided on create.
func (u *ChannelAccountUpsert) UpdateLastRefreshAt() *ChannelAccountUpsert {
	u.SetExcluded(channelaccount.FieldLastRefreshAt)
	return u
}

// ClearLastRefreshAt clears the value of the "last_refresh_at" field.
func (u *ChannelAccountUpsert) ClearLastRefreshAt() *ChannelAccountUpsert {
	u.SetNull(channelaccount.FieldLastRefreshAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ChannelAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChannelAccountUpsertOne) UpdateNewValues() *ChannelAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(channelaccount.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.ChannelID(); exists {
			s.SetIgnore(channelaccount.FieldChannelID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChannelAccount.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChannelAccountUpsertOne) Ignore() *ChannelAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChannelAccountUpsertOne) DoNothing() *ChannelAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChannelAccountCreate.OnConflict
// documentation for more info.
func (u *ChannelAccountUpsertOne) Update(set func(*ChannelAccountUpsert)) *ChannelAccountUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChannelAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelAccountUpsertOne) SetUpdatedAt(v time.Time) *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelAccountUpsertOne) UpdateUpdatedAt() *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ChannelAccountUpsertOne) SetDeletedAt(v int) *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *ChannelAccountUpsertOne) AddDeletedAt(v int) *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ChannelAccountUpsertOne) UpdateDeletedAt() *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *ChannelAccountUpsertOne) SetName(v string) *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ChannelAccountUpsertOne) UpdateName() *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *ChannelAccountUpsertOne) ClearName() *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.ClearName()
	})
}

// SetIdentity sets the "identity" field.
func (u *ChannelAccountUpsertOne) SetIdentity(v string) *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.SetIdentity(v)
	})
}

// UpdateIdentity sets the "identity" field to the value that was provided on create.
func (u *ChannelAccountUpsertOne) UpdateIdentity() *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.UpdateIdentity()
	})
}

// ClearIdentity clears the value of the "identity" field.
func (u *ChannelAccountUpsertOne) ClearIdentity() *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.ClearIdentity()
	})
}

// SetIdentityFingerprint sets the "identity_fingerprint" field.
func (u *ChannelAccountUpsertOne) SetIdentityFingerprint(v string) *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.SetIdentityFingerprint(v)
	})
}

// UpdateIdentityFingerprint sets the "identity_fingerprint" field to the value that was provided on create.
func (u *ChannelAccountUpsertOne) UpdateIdentityFingerprint() *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.UpdateIdentityFingerprint()
	})
}

// ClearIdentityFingerprint clears the value of the "identity_fingerprint" field.
func (u *ChannelAccountUpsertOne) ClearIdentityFingerprint() *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.ClearIdentityFingerprint()
	})
}

// SetCredentials sets the "credentials" field.
func (u *ChannelAccountUpsertOne) SetCredentials(v map[string]interface{}) *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.SetCredentials(v)
	})
}

// UpdateCredentials sets the "credentials" field to the value that was provided on create.
func (u *ChannelAccountUpsertOne) UpdateCredentials() *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.UpdateCredentials()
	})
}

// SetAuthState sets the "auth_state" field.
func (u *ChannelAccountUpsertOne) SetAuthState(v channelaccount.AuthState) *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.SetAuthState(v)
	})
}

// UpdateAuthState sets the "auth_state" field to the value that was provided on create.
func (u *ChannelAccountUpsertOne) UpdateAuthState() *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.UpdateAuthState()
	})
}

// SetAuthErrorCode sets the "auth_error_code" field.
func (u *ChannelAccountUpsertOne) SetAuthErrorCode(v string) *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.SetAuthErrorCode(v)
	})
}

// UpdateAuthErrorCode sets the "auth_error_code" field to the value that was provided on create.
func (u *ChannelAccountUpsertOne) UpdateAuthErrorCode() *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.UpdateAuthErrorCode()
	})
}

// ClearAuthErrorCode clears the value of the "auth_error_code" field.
func (u *ChannelAccountUpsertOne) ClearAuthErrorCode() *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.ClearAuthErrorCode()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ChannelAccountUpsertOne) SetEnabled(v bool) *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ChannelAccountUpsertOne) UpdateEnabled() *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.UpdateEnabled()
	})
}

// SetWeight sets the "weight" field.
func (u *ChannelAccountUpsertOne) SetWeight(v int) *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.SetWeight(v)
	})
}

// AddWeight adds v to the "weight" field.
func (u *ChannelAccountUpsertOne) AddWeight(v int) *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.AddWeight(v)
	})
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *ChannelAccountUpsertOne) UpdateWeight() *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.UpdateWeight()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ChannelAccountUpsertOne) SetExpiresAt(v time.Time) *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ChannelAccountUpsertOne) UpdateExpiresAt() *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ChannelAccountUpsertOne) ClearExpiresAt() *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.ClearExpiresAt()
	})
}

// SetLastRefreshAt sets the "last_refresh_at" field.
func (u *ChannelAccountUpsertOne) SetLastRefreshAt(v time.Time) *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.SetLastRefreshAt(v)
	})
}

// UpdateLastRefreshAt sets the "last_refresh_at" field to the value that was provided on create.
func (u *ChannelAccountUpsertOne) UpdateLastRefreshAt() *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.UpdateLastRefreshAt()
	})
}

// ClearLastRefreshAt clears the value of the "last_refresh_at" field.
func (u *ChannelAccountUpsertOne) ClearLastRefreshAt() *ChannelAccountUpsertOne {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.ClearLastRefreshAt()
	})
}

// Exec executes the query.
func (u *ChannelAccountUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChannelAccountCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChannelAccountUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChannelAccountUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChannelAccountUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChannelAccountCreateBulk is the builder for creating many ChannelAccount entities in bulk.
type ChannelAccountCreateBulk struct {
	config
	err      error
	builders []*ChannelAccountCreate
	conflict []sql.ConflictOption
}

// Save creates the ChannelAccount entities in the database.
func (_c *ChannelAccountCreateBulk) Save(ctx context.Context) ([]*ChannelAccount, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChannelAccount, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChannelAccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChannelAccountCreateBulk) SaveX(ctx context.Context) []*ChannelAccount {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChannelAccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChannelAccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChannelAccount.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChannelAccountUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ChannelAccountCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChannelAccountUpsertBulk {
	_c.conflict = opts
	return &ChannelAccountUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChannelAccount.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChannelAccountCreateBulk) OnConflictColumns(columns ...string) *ChannelAccountUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChannelAccountUpsertBulk{
		create: _c,
	}
}

// ChannelAccountUpsertBulk is the builder for "upsert"-ing
// a bulk of ChannelAccount nodes.
type ChannelAccountUpsertBulk struct {
	create *ChannelAccountCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ChannelAccount.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChannelAccountUpsertBulk) UpdateNewValues() *ChannelAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(channelaccount.FieldCreatedAt)
			}
			if _, exists := b.mutation.ChannelID(); exists {
				s.SetIgnore(channelaccount.FieldChannelID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChannelAccount.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChannelAccountUpsertBulk) Ignore() *ChannelAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChannelAccountUpsertBulk) DoNothing() *ChannelAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChannelAccountCreateBulk.OnConflict
// documentation for more info.
func (u *ChannelAccountUpsertBulk) Update(set func(*ChannelAccountUpsert)) *ChannelAccountUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChannelAccountUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChannelAccountUpsertBulk) SetUpdatedAt(v time.Time) *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChannelAccountUpsertBulk) UpdateUpdatedAt() *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ChannelAccountUpsertBulk) SetDeletedAt(v int) *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.SetDeletedAt(v)
	})
}

// AddDeletedAt adds v to the "deleted_at" field.
func (u *ChannelAccountUpsertBulk) AddDeletedAt(v int) *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.AddDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ChannelAccountUpsertBulk) UpdateDeletedAt() *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.UpdateDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *ChannelAccountUpsertBulk) SetName(v string) *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ChannelAccountUpsertBulk) UpdateName() *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *ChannelAccountUpsertBulk) ClearName() *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.ClearName()
	})
}

// SetIdentity sets the "identity" field.
func (u *ChannelAccountUpsertBulk) SetIdentity(v string) *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.SetIdentity(v)
	})
}

// UpdateIdentity sets the "identity" field to the value that was provided on create.
func (u *ChannelAccountUpsertBulk) UpdateIdentity() *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.UpdateIdentity()
	})
}

// ClearIdentity clears the value of the "identity" field.
func (u *ChannelAccountUpsertBulk) ClearIdentity() *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.ClearIdentity()
	})
}

// SetIdentityFingerprint sets the "identity_fingerprint" field.
func (u *ChannelAccountUpsertBulk) SetIdentityFingerprint(v string) *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.SetIdentityFingerprint(v)
	})
}

// UpdateIdentityFingerprint sets the "identity_fingerprint" field to the value that was provided on create.
func (u *ChannelAccountUpsertBulk) UpdateIdentityFingerprint() *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.UpdateIdentityFingerprint()
	})
}

// ClearIdentityFingerprint clears the value of the "identity_fingerprint" field.
func (u *ChannelAccountUpsertBulk) ClearIdentityFingerprint() *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.ClearIdentityFingerprint()
	})
}

// SetCredentials sets the "credentials" field.
func (u *ChannelAccountUpsertBulk) SetCredentials(v map[string]interface{}) *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.SetCredentials(v)
	})
}

// UpdateCredentials sets the "credentials" field to the value that was provided on create.
func (u *ChannelAccountUpsertBulk) UpdateCredentials() *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.UpdateCredentials()
	})
}

// SetAuthState sets the "auth_state" field.
func (u *ChannelAccountUpsertBulk) SetAuthState(v channelaccount.AuthState) *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.SetAuthState(v)
	})
}

// UpdateAuthState sets the "auth_state" field to the value that was provided on create.
func (u *ChannelAccountUpsertBulk) UpdateAuthState() *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.UpdateAuthState()
	})
}

// SetAuthErrorCode sets the "auth_error_code" field.
func (u *ChannelAccountUpsertBulk) SetAuthErrorCode(v string) *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.SetAuthErrorCode(v)
	})
}

// UpdateAuthErrorCode sets the "auth_error_code" field to the value that was provided on create.
func (u *ChannelAccountUpsertBulk) UpdateAuthErrorCode() *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.UpdateAuthErrorCode()
	})
}

// ClearAuthErrorCode clears the value of the "auth_error_code" field.
func (u *ChannelAccountUpsertBulk) ClearAuthErrorCode() *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.ClearAuthErrorCode()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ChannelAccountUpsertBulk) SetEnabled(v bool) *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ChannelAccountUpsertBulk) UpdateEnabled() *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.UpdateEnabled()
	})
}

// SetWeight sets the "weight" field.
func (u *ChannelAccountUpsertBulk) SetWeight(v int) *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.SetWeight(v)
	})
}

// AddWeight adds v to the "weight" field.
func (u *ChannelAccountUpsertBulk) AddWeight(v int) *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.AddWeight(v)
	})
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *ChannelAccountUpsertBulk) UpdateWeight() *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.UpdateWeight()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *ChannelAccountUpsertBulk) SetExpiresAt(v time.Time) *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *ChannelAccountUpsertBulk) UpdateExpiresAt() *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.UpdateExpiresAt()
	})
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (u *ChannelAccountUpsertBulk) ClearExpiresAt() *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.ClearExpiresAt()
	})
}

// SetLastRefreshAt sets the "last_refresh_at" field.
func (u *ChannelAccountUpsertBulk) SetLastRefreshAt(v time.Time) *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.SetLastRefreshAt(v)
	})
}

// UpdateLastRefreshAt sets the "last_refresh_at" field to the value that was provided on create.
func (u *ChannelAccountUpsertBulk) UpdateLastRefreshAt() *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.UpdateLastRefreshAt()
	})
}

// ClearLastRefreshAt clears the value of the "last_refresh_at" field.
func (u *ChannelAccountUpsertBulk) ClearLastRefreshAt() *ChannelAccountUpsertBulk {
	return u.Update(func(s *ChannelAccountUpsert) {
		s.ClearLastRefreshAt()
	})
}

// Exec executes the query.
func (u *ChannelAccountUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChannelAccountCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChannelAccountCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChannelAccountUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
