// Code generated by ent, DO NOT EDIT.

package channelaccount

import (
	"fmt"
	"io"
	"strconv"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the channelaccount type in the database.
	Label = "channel_account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldChannelID holds the string denoting the channel_id field in the database.
	FieldChannelID = "channel_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldIdentity holds the string denoting the identity field in the database.
	FieldIdentity = "identity"
	// FieldIdentityFingerprint holds the string denoting the identity_fingerprint field in the database.
	FieldIdentityFingerprint = "identity_fingerprint"
	// FieldCredentials holds the string denoting the credentials field in the database.
	FieldCredentials = "credentials"
	// FieldAuthState holds the string denoting the auth_state field in the database.
	FieldAuthState = "auth_state"
	// FieldAuthErrorCode holds the string denoting the auth_error_code field in the database.
	FieldAuthErrorCode = "auth_error_code"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldWeight holds the string denoting the weight field in the database.
	FieldWeight = "weight"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldLastRefreshAt holds the string denoting the last_refresh_at field in the database.
	FieldLastRefreshAt = "last_refresh_at"
	// EdgeChannel holds the string denoting the channel edge name in mutations.
	EdgeChannel = "channel"
	// Table holds the table name of the channelaccount in the database.
	Table = "channel_accounts"
	// ChannelTable is the table that holds the channel relation/edge.
	ChannelTable = "channel_accounts"
	// ChannelInverseTable is the table name for the Channel entity.
	// It exists in this package in order to avoid circular dependency with the "channel" package.
	ChannelInverseTable = "channels"
	// ChannelColumn is the table column denoting the channel relation/edge.
	ChannelColumn = "channel_id"
)

// Columns holds all SQL columns for channelaccount fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldChannelID,
	FieldName,
	FieldIdentity,
	FieldIdentityFingerprint,
	FieldCredentials,
	FieldAuthState,
	FieldAuthErrorCode,
	FieldEnabled,
	FieldWeight,
	FieldExpiresAt,
	FieldLastRefreshAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/looplj/axonhub/internal/ent/runtime"
var (
	Hooks        [2]ent.Hook
	Interceptors [1]ent.Interceptor
	Policy       ent.Policy
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt int
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// DefaultIdentity holds the default value on creation for the "identity" field.
	DefaultIdentity string
	// DefaultIdentityFingerprint holds the default value on creation for the "identity_fingerprint" field.
	DefaultIdentityFingerprint string
	// DefaultAuthErrorCode holds the default value on creation for the "auth_error_code" field.
	DefaultAuthErrorCode string
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultWeight holds the default value on creation for the "weight" field.
	DefaultWeight int
)

// AuthState defines the type for the "auth_state" enum field.
type AuthState string

// AuthStateReady is the default value of the AuthState enum.
const DefaultAuthState = AuthStateReady

// AuthState values.
const (
	AuthStateReady                   AuthState = "ready"
	AuthStateRefreshing              AuthState = "refreshing"
	AuthStateReauthorizationRequired AuthState = "reauthorization_required"
	AuthStateOutcomeUnknown          AuthState = "outcome_unknown"
)

func (as AuthState) String() string {
	return string(as)
}

// AuthStateValidator is a validator for the "auth_state" field enum values. It is called by the builders before save.
func AuthStateValidator(as AuthState) error {
	switch as {
	case AuthStateReady, AuthStateRefreshing, AuthStateReauthorizationRequired, AuthStateOutcomeUnknown:
		return nil
	default:
		return fmt.Errorf("channelaccount: invalid enum value for auth_state field: %q", as)
	}
}

// OrderOption defines the ordering options for the ChannelAccount queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByChannelID orders the results by the channel_id field.
func ByChannelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannelID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByIdentity orders the results by the identity field.
func ByIdentity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdentity, opts...).ToFunc()
}

// ByIdentityFingerprint orders the results by the identity_fingerprint field.
func ByIdentityFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdentityFingerprint, opts...).ToFunc()
}

// ByAuthState orders the results by the auth_state field.
func ByAuthState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthState, opts...).ToFunc()
}

// ByAuthErrorCode orders the results by the auth_error_code field.
func ByAuthErrorCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthErrorCode, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByWeight orders the results by the weight field.
func ByWeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeight, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByLastRefreshAt orders the results by the last_refresh_at field.
func ByLastRefreshAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastRefreshAt, opts...).ToFunc()
}

// ByChannelField orders the results by channel field.
func ByChannelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChannelStep(), sql.OrderByField(field, opts...))
	}
}
func newChannelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChannelInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ChannelTable, ChannelColumn),
	)
}

// MarshalGQL implements graphql.Marshaler interface.
func (e AuthState) MarshalGQL(w io.Writer) {
	io.WriteString(w, strconv.Quote(e.String()))
}

// UnmarshalGQL implements graphql.Unmarshaler interface.
func (e *AuthState) UnmarshalGQL(val interface{}) error {
	str, ok := val.(string)
	if !ok {
		return fmt.Errorf("enum %T must be a string", val)
	}
	*e = AuthState(str)
	if err := AuthStateValidator(*e); err != nil {
		return fmt.Errorf("%s is not a valid AuthState", str)
	}
	return nil
}
