// Code generated by ent, DO NOT EDIT.

package channelaccount

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/looplj/axonhub/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEQ(FieldDeletedAt, v))
}

// ChannelID applies equality check predicate on the "channel_id" field. It's identical to ChannelIDEQ.
func ChannelID(v int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEQ(FieldChannelID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEQ(FieldName, v))
}

// Identity applies equality check predicate on the "identity" field. It's identical to IdentityEQ.
func Identity(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEQ(FieldIdentity, v))
}

// IdentityFingerprint applies equality check predicate on the "identity_fingerprint" field. It's identical to IdentityFingerprintEQ.
func IdentityFingerprint(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEQ(FieldIdentityFingerprint, v))
}

// AuthErrorCode applies equality check predicate on the "auth_error_code" field. It's identical to AuthErrorCodeEQ.
func AuthErrorCode(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEQ(FieldAuthErrorCode, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEQ(FieldEnabled, v))
}

// Weight applies equality check predicate on the "weight" field. It's identical to WeightEQ.
func Weight(v int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEQ(FieldWeight, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEQ(FieldExpiresAt, v))
}

// LastRefreshAt applies equality check predicate on the "last_refresh_at" field. It's identical to LastRefreshAtEQ.
func LastRefreshAt(v time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEQ(FieldLastRefreshAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldLTE(FieldDeletedAt, v))
}

// ChannelIDEQ applies the EQ predicate on the "channel_id" field.
func ChannelIDEQ(v int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEQ(FieldChannelID, v))
}

// ChannelIDNEQ applies the NEQ predicate on the "channel_id" field.
func ChannelIDNEQ(v int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNEQ(FieldChannelID, v))
}

// ChannelIDIn applies the In predicate on the "channel_id" field.
func ChannelIDIn(vs ...int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldIn(FieldChannelID, vs...))
}

// ChannelIDNotIn applies the NotIn predicate on the "channel_id" field.
func ChannelIDNotIn(vs ...int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNotIn(FieldChannelID, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldContainsFold(FieldName, v))
}

// IdentityEQ applies the EQ predicate on the "identity" field.
func IdentityEQ(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEQ(FieldIdentity, v))
}

// IdentityNEQ applies the NEQ predicate on the "identity" field.
func IdentityNEQ(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNEQ(FieldIdentity, v))
}

// IdentityIn applies the In predicate on the "identity" field.
func IdentityIn(vs ...string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldIn(FieldIdentity, vs...))
}

// IdentityNotIn applies the NotIn predicate on the "identity" field.
func IdentityNotIn(vs ...string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNotIn(FieldIdentity, vs...))
}

// IdentityGT applies the GT predicate on the "identity" field.
func IdentityGT(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldGT(FieldIdentity, v))
}

// IdentityGTE applies the GTE predicate on the "identity" field.
func IdentityGTE(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldGTE(FieldIdentity, v))
}

// IdentityLT applies the LT predicate on the "identity" field.
func IdentityLT(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldLT(FieldIdentity, v))
}

// IdentityLTE applies the LTE predicate on the "identity" field.
func IdentityLTE(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldLTE(FieldIdentity, v))
}

// IdentityContains applies the Contains predicate on the "identity" field.
func IdentityContains(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldContains(FieldIdentity, v))
}

// IdentityHasPrefix applies the HasPrefix predicate on the "identity" field.
func IdentityHasPrefix(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldHasPrefix(FieldIdentity, v))
}

// IdentityHasSuffix applies the HasSuffix predicate on the "identity" field.
func IdentityHasSuffix(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldHasSuffix(FieldIdentity, v))
}

// IdentityIsNil applies the IsNil predicate on the "identity" field.
func IdentityIsNil() predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldIsNull(FieldIdentity))
}

// IdentityNotNil applies the NotNil predicate on the "identity" field.
func IdentityNotNil() predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNotNull(FieldIdentity))
}

// IdentityEqualFold applies the EqualFold predicate on the "identity" field.
func IdentityEqualFold(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEqualFold(FieldIdentity, v))
}

// IdentityContainsFold applies the ContainsFold predicate on the "identity" field.
func IdentityContainsFold(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldContainsFold(FieldIdentity, v))
}

// IdentityFingerprintEQ applies the EQ predicate on the "identity_fingerprint" field.
func IdentityFingerprintEQ(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEQ(FieldIdentityFingerprint, v))
}

// IdentityFingerprintNEQ applies the NEQ predicate on the "identity_fingerprint" field.
func IdentityFingerprintNEQ(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNEQ(FieldIdentityFingerprint, v))
}

// IdentityFingerprintIn applies the In predicate on the "identity_fingerprint" field.
func IdentityFingerprintIn(vs ...string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldIn(FieldIdentityFingerprint, vs...))
}

// IdentityFingerprintNotIn applies the NotIn predicate on the "identity_fingerprint" field.
func IdentityFingerprintNotIn(vs ...string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNotIn(FieldIdentityFingerprint, vs...))
}

// IdentityFingerprintGT applies the GT predicate on the "identity_fingerprint" field.
func IdentityFingerprintGT(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldGT(FieldIdentityFingerprint, v))
}

// IdentityFingerprintGTE applies the GTE predicate on the "identity_fingerprint" field.
func IdentityFingerprintGTE(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldGTE(FieldIdentityFingerprint, v))
}

// IdentityFingerprintLT applies the LT predicate on the "identity_fingerprint" field.
func IdentityFingerprintLT(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldLT(FieldIdentityFingerprint, v))
}

// IdentityFingerprintLTE applies the LTE predicate on the "identity_fingerprint" field.
func IdentityFingerprintLTE(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldLTE(FieldIdentityFingerprint, v))
}

// IdentityFingerprintContains applies the Contains predicate on the "identity_fingerprint" field.
func IdentityFingerprintContains(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldContains(FieldIdentityFingerprint, v))
}

// IdentityFingerprintHasPrefix applies the HasPrefix predicate on the "identity_fingerprint" field.
func IdentityFingerprintHasPrefix(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldHasPrefix(FieldIdentityFingerprint, v))
}

// IdentityFingerprintHasSuffix applies the HasSuffix predicate on the "identity_fingerprint" field.
func IdentityFingerprintHasSuffix(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldHasSuffix(FieldIdentityFingerprint, v))
}

// IdentityFingerprintIsNil applies the IsNil predicate on the "identity_fingerprint" field.
func IdentityFingerprintIsNil() predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldIsNull(FieldIdentityFingerprint))
}

// IdentityFingerprintNotNil applies the NotNil predicate on the "identity_fingerprint" field.
func IdentityFingerprintNotNil() predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNotNull(FieldIdentityFingerprint))
}

// IdentityFingerprintEqualFold applies the EqualFold predicate on the "identity_fingerprint" field.
func IdentityFingerprintEqualFold(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEqualFold(FieldIdentityFingerprint, v))
}

// IdentityFingerprintContainsFold applies the ContainsFold predicate on the "identity_fingerprint" field.
func IdentityFingerprintContainsFold(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldContainsFold(FieldIdentityFingerprint, v))
}

// AuthStateEQ applies the EQ predicate on the "auth_state" field.
func AuthStateEQ(v AuthState) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEQ(FieldAuthState, v))
}

// AuthStateNEQ applies the NEQ predicate on the "auth_state" field.
func AuthStateNEQ(v AuthState) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNEQ(FieldAuthState, v))
}

// AuthStateIn applies the In predicate on the "auth_state" field.
func AuthStateIn(vs ...AuthState) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldIn(FieldAuthState, vs...))
}

// AuthStateNotIn applies the NotIn predicate on the "auth_state" field.
func AuthStateNotIn(vs ...AuthState) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNotIn(FieldAuthState, vs...))
}

// AuthErrorCodeEQ applies the EQ predicate on the "auth_error_code" field.
func AuthErrorCodeEQ(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEQ(FieldAuthErrorCode, v))
}

// AuthErrorCodeNEQ applies the NEQ predicate on the "auth_error_code" field.
func AuthErrorCodeNEQ(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNEQ(FieldAuthErrorCode, v))
}

// AuthErrorCodeIn applies the In predicate on the "auth_error_code" field.
func AuthErrorCodeIn(vs ...string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldIn(FieldAuthErrorCode, vs...))
}

// AuthErrorCodeNotIn applies the NotIn predicate on the "auth_error_code" field.
func AuthErrorCodeNotIn(vs ...string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNotIn(FieldAuthErrorCode, vs...))
}

// AuthErrorCodeGT applies the GT predicate on the "auth_error_code" field.
func AuthErrorCodeGT(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldGT(FieldAuthErrorCode, v))
}

// AuthErrorCodeGTE applies the GTE predicate on the "auth_error_code" field.
func AuthErrorCodeGTE(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldGTE(FieldAuthErrorCode, v))
}

// AuthErrorCodeLT applies the LT predicate on the "auth_error_code" field.
func AuthErrorCodeLT(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldLT(FieldAuthErrorCode, v))
}

// AuthErrorCodeLTE applies the LTE predicate on the "auth_error_code" field.
func AuthErrorCodeLTE(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldLTE(FieldAuthErrorCode, v))
}

// AuthErrorCodeContains applies the Contains predicate on the "auth_error_code" field.
func AuthErrorCodeContains(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldContains(FieldAuthErrorCode, v))
}

// AuthErrorCodeHasPrefix applies the HasPrefix predicate on the "auth_error_code" field.
func AuthErrorCodeHasPrefix(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldHasPrefix(FieldAuthErrorCode, v))
}

// AuthErrorCodeHasSuffix applies the HasSuffix predicate on the "auth_error_code" field.
func AuthErrorCodeHasSuffix(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldHasSuffix(FieldAuthErrorCode, v))
}

// AuthErrorCodeIsNil applies the IsNil predicate on the "auth_error_code" field.
func AuthErrorCodeIsNil() predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldIsNull(FieldAuthErrorCode))
}

// AuthErrorCodeNotNil applies the NotNil predicate on the "auth_error_code" field.
func AuthErrorCodeNotNil() predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNotNull(FieldAuthErrorCode))
}

// AuthErrorCodeEqualFold applies the EqualFold predicate on the "auth_error_code" field.
func AuthErrorCodeEqualFold(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEqualFold(FieldAuthErrorCode, v))
}

// AuthErrorCodeContainsFold applies the ContainsFold predicate on the "auth_error_code" field.
func AuthErrorCodeContainsFold(v string) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldContainsFold(FieldAuthErrorCode, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNEQ(FieldEnabled, v))
}

// WeightEQ applies the EQ predicate on the "weight" field.
func WeightEQ(v int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEQ(FieldWeight, v))
}

// WeightNEQ applies the NEQ predicate on the "weight" field.
func WeightNEQ(v int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNEQ(FieldWeight, v))
}

// WeightIn applies the In predicate on the "weight" field.
func WeightIn(vs ...int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldIn(FieldWeight, vs...))
}

// WeightNotIn applies the NotIn predicate on the "weight" field.
func WeightNotIn(vs ...int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNotIn(FieldWeight, vs...))
}

// WeightGT applies the GT predicate on the "weight" field.
func WeightGT(v int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldGT(FieldWeight, v))
}

// WeightGTE applies the GTE predicate on the "weight" field.
func WeightGTE(v int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldGTE(FieldWeight, v))
}

// WeightLT applies the LT predicate on the "weight" field.
func WeightLT(v int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldLT(FieldWeight, v))
}

// WeightLTE applies the LTE predicate on the "weight" field.
func WeightLTE(v int) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldLTE(FieldWeight, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNotNull(FieldExpiresAt))
}

// LastRefreshAtEQ applies the EQ predicate on the "last_refresh_at" field.
func LastRefreshAtEQ(v time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldEQ(FieldLastRefreshAt, v))
}

// LastRefreshAtNEQ applies the NEQ predicate on the "last_refresh_at" field.
func LastRefreshAtNEQ(v time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNEQ(FieldLastRefreshAt, v))
}

// LastRefreshAtIn applies the In predicate on the "last_refresh_at" field.
func LastRefreshAtIn(vs ...time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldIn(FieldLastRefreshAt, vs...))
}

// LastRefreshAtNotIn applies the NotIn predicate on the "last_refresh_at" field.
func LastRefreshAtNotIn(vs ...time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNotIn(FieldLastRefreshAt, vs...))
}

// LastRefreshAtGT applies the GT predicate on the "last_refresh_at" field.
func LastRefreshAtGT(v time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldGT(FieldLastRefreshAt, v))
}

// LastRefreshAtGTE applies the GTE predicate on the "last_refresh_at" field.
func LastRefreshAtGTE(v time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldGTE(FieldLastRefreshAt, v))
}

// LastRefreshAtLT applies the LT predicate on the "last_refresh_at" field.
func LastRefreshAtLT(v time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldLT(FieldLastRefreshAt, v))
}

// LastRefreshAtLTE applies the LTE predicate on the "last_refresh_at" field.
func LastRefreshAtLTE(v time.Time) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldLTE(FieldLastRefreshAt, v))
}

// LastRefreshAtIsNil applies the IsNil predicate on the "last_refresh_at" field.
func LastRefreshAtIsNil() predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldIsNull(FieldLastRefreshAt))
}

// LastRefreshAtNotNil applies the NotNil predicate on the "last_refresh_at" field.
func LastRefreshAtNotNil() predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.FieldNotNull(FieldLastRefreshAt))
}

// HasChannel applies the HasEdge predicate on the "channel" edge.
func HasChannel() predicate.ChannelAccount {
	return predicate.ChannelAccount(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ChannelTable, ChannelColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChannelWith applies the HasEdge predicate on the "channel" edge with a given conditions (other predicates).
func HasChannelWith(preds ...predicate.Channel) predicate.ChannelAccount {
	return predicate.ChannelAccount(func(s *sql.Selector) {
		step := newChannelStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChannelAccount) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChannelAccount) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChannelAccount) predicate.ChannelAccount {
	return predicate.ChannelAccount(sql.NotPredicates(p))
}
